Replace usage of internal class ClosureBackedAction
In a commit for Gradle 5.0 the internal class `org.gradle.api.internal.ClosureBackedAction` 
has been moved to org.gradle.util.ClosureBackedAction` 
(see https://github.com/gradle/gradle/commit/b16479080a8864f91d15540d41bc09bdbe2c0af3#diff-bd993f7b907baefcd8fcf66327841ed4).

This commit replaces the usage of `ClosureBackedAction` with `org.gradle.util.ConfigureUtil.configureUsing()`
which is available for a long time.

This fixes an exception when the plugin is used nightly builds of Gradle 5.0:
`java.lang.NoClassDefFoundError: org/gradle/api/internal/ClosureBackedAction`